### ISSUE TITLE
Incompatibility with aliases

### ISSUE THREAD

**Issue by atishaybaid7** [arcanis/pnp-webpack-plugin#1] opened 2018-10-10 16:12 UTC
@arcanis 
When adding webpack plugin to resolve imports,it is not able to resolve files in entry and other places.
`webpack :v4.17.1`
`yarn : v1.12.0`
`node:v8.11.3`

<img width="1437" alt="screen shot 2018-10-10 at 4 45 36 pm" src="https://user-images.githubusercontent.com/40356338/46750247-296e6080-ccd5-11e8-8b89-ab85bf3fb250.png">

webpack entry

`
entry: {
            polyfills: path.resolve(__dirname, "../src", "polyfills/polyfills"),
            application: "production",
            vendor: ["react", "react-dom", "redux-saga", "react-redux", "redux-json-router", "redux", "axios",
                "lodash", "highcharts"],
            extras: ["extras"]
        },
`

**Comment by ankurk91** [comment] 2018-11-01 15:56
I have the same issue
I have an existing [repo](https://github.com/ankurk91/vue-flatpickr-component).

```
yarn install --pnp
yarn add pnp-webpack-plugin --dev
yarn run docs
```

```
yarn run v1.12.1
$ cross-env NODE_ENV=development webpack-serve --config=webpack.config.dev.js > webpack.log
✖ ｢config｣: An error occurred while trying to load /Users/ankurk/projects/p/vue-flatpickr-component/webpack.config.dev.js
              Did you forget to specify a --require?
/Users/ankurk/Library/Caches/Yarn/v3/npm-@webpack-contrib-config-loader-1.2.1-5b3dd474e207437939d294d200c68b7b00008e04/node_modules/@webpack-contrib/config-loader/lib/load.js:85
    throw new LoadConfigError(e, configPath);
    ^

LoadConfigError: You cannot require a package ("uglifyjs-webpack-plugin") that is not declared in your dependencies (via "/Users/ankurk/projects/p/vue-flatpickr-component/webpack.config.dev.js")
    at makeError (/Users/ankurk/projects/p/vue-flatpickr-component/.pnp.js:54:17)
    at Object.resolveToUnqualified (/Users/ankurk/projects/p/vue-flatpickr-component/.pnp.js:11435:17)
    at Object.resolveRequest (/Users/ankurk/projects/p/vue-flatpickr-component/.pnp.js:11513:31)
    at Function.Module._resolveFilename (/Users/ankurk/projects/p/vue-flatpickr-component/.pnp.js:11693:30)
    at Function.Module._load (/Users/ankurk/projects/p/vue-flatpickr-component/.pnp.js:11611:31)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/Users/ankurk/Library/Caches/Yarn/v3/npm-v8-compile-cache-2.0.0-526492e35fc616864284700b7043e01baee09f0a/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/ankurk/projects/p/vue-flatpickr-component/webpack.config.dev.js:9:24)
    at Module._compile (/Users/ankurk/Library/Caches/Yarn/v3/npm-v8-compile-cache-2.0.0-526492e35fc616864284700b7043e01baee09f0a/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at Function.Module._load (/Users/ankurk/projects/p/vue-flatpickr-component/.pnp.js:11638:14)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/Users/ankurk/Library/Caches/Yarn/v3/npm-v8-compile-cache-2.0.0-526492e35fc616864284700b7043e01baee09f0a/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadJs (/Users/ankurk/Library/Caches/Yarn/v3/npm-cosmiconfig-5.0.5-a809e3c2306891ce17ab70359dc8bdf661fe2cd0/node_modules/cosmiconfig/dist/loaders.js:8:18)
    at Explorer.loadFileContent (/Users/ankurk/Library/Caches/Yarn/v3/npm-cosmiconfig-5.0.5-a809e3c2306891ce17ab70359dc8bdf661fe2cd0/node_modules/cosmiconfig/dist/createExplorer.js:226:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To resolve this issue, i had to alter my webpack configs.**
* Remove any alias
* Remove provide plugin entries
* add `require.resolve()` to loader names

Then i am getting this error
```
yarn run v1.12.1
$ cross-env NODE_ENV=production webpack --config=webpack.config.dev.js --progress --mode production
Hash: fc843bc70d9714a3b3f7                                                             
Version: webpack 4.18.0
Time: 975ms
Built at: 11/01/2018 9:22:34 PM
Entrypoint main =

ERROR in ./examples/index.js
Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/index.js 15:0-46

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 194:0-34 197:0-9
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./src/component.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./src/component.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr' in '/Users/ankurk/projects/p/vue-flatpickr-component/src'
 @ ./src/component.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./src/component.vue?vue&type=script&lang=js&) 6:0-34 78:18-27
 @ ./src/component.vue?vue&type=script&lang=js&
 @ ./src/component.vue
 @ ./src/index.js
 @ /Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr/dist/flatpickr.min.css' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 207:0-42
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr/dist/l10n/default.js' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 210:0-74 295:47-60
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr/dist/l10n/hi.js' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 209:0-65 255:18-29
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr/dist/plugins/confirmDate/confirmDate.css' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 215:0-60
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'flatpickr/dist/plugins/confirmDate/confirmDate.js' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 214:0-82 265:24-41
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/index.js
Module not found: Error: Can't resolve 'vee-validate' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/index.js 8:0-39 10:8-19

ERROR in ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/App.vue?vue&type=script&lang=js& (/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib!/Users/ankurk/Library/Caches/Yarn/v3/npm-vue-loader-15.4.1-10c2da6f50ce5fc6bff2317dcbd1dccf4b3c7702/node_modules/vue-loader/lib??vue-loader-options!./examples/App.vue?vue&type=script&lang=js&) 193:0-22 204:0-3
 @ ./examples/App.vue?vue&type=script&lang=js&
 @ ./examples/App.vue
 @ ./examples/index.js

ERROR in ./examples/index.js
Module not found: Error: Can't resolve 'vue' in '/Users/ankurk/projects/p/vue-flatpickr-component/examples'
 @ ./examples/index.js 3:0-22 5:0-3 10:0-3 19:4-7

ERROR in chunk main [entry]
js/main.fc843bc70d9714a3b3f7.js
/Users/ankurk/Library/Caches/Yarn/v3/npm-babel-loader-7.1.5-e3ee0cd7394aa557e013b02d3e492bfd07aa6d68/node_modules/babel-loader/lib/index.js!/Users/ankurk/projects/p/vue-flatpickr-component/examples/index.js b41f6db422bec71ab57fff51a37500bb
Unexpected token (79:18)
| 
|     // Init flatpickr
|     this.fp = new !(function webpackMissingModule() { var e = new Error("Cannot find module 'flatpickr'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(this.getElem(), safeConfig);
| 
|     // Attach blur event
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by arcanis** [comment] 2018-11-01 16:19
I think the problem comes from where the plugin injects itself inbetween [the various `enhanced-resolve` steps](https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L154-L167).

Right now, [it's plugged on `before-module`](https://github.com/arcanis/pnp-webpack-plugin/blob/master/index.js#L60) and [jumps to `resolve` once done](https://github.com/arcanis/pnp-webpack-plugin/blob/master/index.js#L48). I figured that's what had to be done in order to let Webpack resolve the extensions, mains, and `index.js`, but maybe it shortcuts the aliases?

cc @sokra, could you share your expertise?

**Comment by sokra** [comment] 2018-11-01 17:52
Sounds good.

**Comment by arcanis** [comment] 2018-11-01 18:44
It sounds but it isn't 😅 

It seems like the aliased module doesn't even go inside the `before-module` hook - if I put a `console.log` there it never gets called with the aliased string (but everything else goes as usual). No idea? The enhanced-resolve flow isn't easy to follow.

**Comment by sokra** [comment] 2018-11-01 19:01
After aliased it starts over at `resolve`, so should be identical to using the same request directly.

`--display-error-details` displays the resolve flow in the errors.

**Comment by arcanis** [comment] 2018-11-01 20:30
> `--display-error-details` displays the resolve flow in the errors.

Sweet, I didn't know that, thanks!

--- 

So.

- @ankurk91 The problem is in your repo 😉 As the error message tells you, you're trying to require a package (`uglifyjs-webpack-plugin`) without it being defined in your dependencies. Just run `yarn add --dev uglifyjs-webpack-plugin` and it will work (I tried it).

- @atishaybaid7 I haven't been able to reproduce the error you mentioned. I've also confirmed that both alias entries and entry bundles can be correctly resolved by the plugin. If you still have this issue, please provide me a repository where I can reproduce the issue (like @ankurk91 did) so that I can pinpoint the reason.

Since the issue described in the title cannot be reproduced at the moment I'm going to close this issue. @atishaybaid7, feel free to reopen it once you have more information!

**Closed by arcanis** 2018-11-01 20:30 UTC

**Comment by arcanis** [comment] 2018-11-01 20:32
Also @ankurk91, the second errors you mentioned seem to be caused by missing `plugins` entries in your configuration. I've tried with the exact same setup than the one described on the usage page of pnp-webpack-bundle, and it worked fine: https://github.com/arcanis/pnp-webpack-plugin#usage

**Comment by rhaksw** [comment] 2020-03-18 07:44
While adding this plugin for yarn 2, I had the same "Can't resolve..." issue as @ankurk91 above until I realized when following the usage instructions I had defined the `resolve` entry twice,

```
  resolve: {
    modules: [path.resolve(__dirname, 'src'), 'node_modules'],
  },
...
  resolve: {
    plugins: [
      PnpWebpackPlugin,
    ],
  },
  resolveLoader: {
    plugins: [
      PnpWebpackPlugin.moduleLoader(module),
    ],
  },
```

I don't touch my webpack config often and had forgotten I already had a `resolve` entry in there. Maybe this will help someone else!
